apiVersion: apps/v1
kind: Deployment
metadata:
  name: valueservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valueservice
  template:
    metadata:
      labels:
        app: valueservice
    spec:
      containers:
      - name: valueservice
        image: 127.0.0.1/internal/valueservice:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: valueservice
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: harborcred
